<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Refit.HttpClientFactory" Version="10.1.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Security\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ControlGo.Application\ControlGo.Application.csproj" />
    <ProjectReference Include="..\ControlGo.Domain\ControlGo.Domain.csproj" />
    <ProjectReference Include="..\ControlGo.Infrastructure\ControlGo.Infrastructure.csproj" />
  </ItemGroup>

</Project>
