image:
  repository: "#{registry_server_name}#"
  name: "#{project_name}#"
  pullPolicy: Always
  tag: "#{app_version}#"


imagePullSecrets:
  - name: 

serviceAccount:
  create: false
  name:

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000

service:
  type: ClusterIP
  port:

environment:

env:

resources:
  limits:
    cpu:
    memory:
  requests:
    cpu:
    memory:

replicas:

autoscaling:
  enabled:
  minReplicas:
  maxReplicas:
  targetMemoryUtilizationPercentage:
  targetCPUUtilizationPercentage:

labels:
  app.kubernetes.io/managed-by: "Helm"


buildInformation:
  branchName: "#{Build.SourceBranch}#"
  sourceVersion: "#{Build.SourceVersion}#"
  buildId: "#{app_version}#"
  appVersion: "#{app_version}#"  

#begin config Applications

database:
  connectionString:

redis:
  enabled:
  host:
  instanceName:

rabbitMQ:
  host: 
  queueName:
  username:
  password:

applicationInsights:
  connectionString:

#end config Applications