image:
  repository: "#{registry_server_name}#"
  name: "#{project_name}#"
  pullPolicy: Always
  tag: "#{app_version}#"


imagePullSecrets:
  - name: 

serviceAccount:
  create: false
  name:

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000

service:
  type: ClusterIP
  port:

environment:

env:

resources:
  limits:
    cpu:
    memory:
  requests:
    cpu:
    memory:

replicas:

autoscaling:
  enabled:
  minReplicas:
  maxReplicas:
  targetMemoryUtilizationPercentage:
  targetCPUUtilizationPercentage:

labels:
  app.kubernetes.io/managed-by: "Helm"

buildInformation:
  branchName: "#{Build.SourceBranch}#"
  sourceVersion: "#{Build.SourceVersion}#"
  buildId: "#{Build.BuildId}#"
  appVersion: "#{app_version}#"
  author: "#{Build.RequestedFor}#"

logs:
  lokiServiceUrl:

database:
  connectionString:

redis:
  enabled:
  host:
  databaseId:

app:
  cacheJWTTokens: false
  serverRootAddress:
  internalServerRootAddress:
  clientRootAddress:

fileConfiguration:
  blobStorage:
    isEnabled: true
    storageAccount:
    accessKey:
    storageAccountBackup:
    accessKeyBackup:
  local:
    sourceDirectory: /var/lib/compliance-backend/files
    backupDirectory: /var/lib/compliance-backend/backups

reCaptcha:
  siteKey:
  secretKey:

identityServer:
  authority:
  
applicationInsights:
  connectionString: