apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "manifest.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- include "manifest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "manifest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "manifest.defaultAnnotations" . | nindent 8 }}
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "manifest.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "manifest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name  }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- with .Values.defaultEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: config-volume
              subPath: appsettings.json
            {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: appsettings.json
                path: appsettings.json
              - key: log4net.config
                path: log4net.config
            name: {{ include "manifest.fullname" . }}
          name: config-volume  
        {{- with .Values.volumes }}
            {{- toYaml . | nindent 8 }}
        {{- end }}


