name: Build

on:
  pull_request:
    branches: [develop, main]
    types: [opened, reopened]
      # - 'develop'           
      # - 'hotfix/*'
      # - 'bugfix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        ARTIFACT_NAME: 'dotnet-core-template'        
        PROJECT_NAME: 'Worldsys.API'
    steps:
      # - name: Clean build directory
      # run: rm -rf ./path/to/build/directory/*
        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha}}
      - name: Pull and checking out from git repository
        run: |
           echo "Pull and checking out from git repository finished Ok"
           
      # - name: Validate branch name
        # run: |
          # PR_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          # if [[ "$PR_BRANCH" != feature/* && "$PR_BRANCH" != hotfix/* && "$PR_BRANCH" != bugfix/* ]]; then
            # echo "Pull requests are only allowed from branches with feature, hotfix, or bugfix names."
            # exit 1
          # fi

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release