# ci-variables.yml
variables:
  CSPROJ_PATH: 'Worldsys.API\Worldsys.API.csproj'
  SLN_PATH: "./*.sln"
  PROJECT_NAME: "complianceone-microservice-Worldsys.API"
  ARTIFACT_NAME: "complianceone-microservice-Worldsys.API-build"
  REPOSITORY_URL: "https://github.com/tu-usuario/tu-repositorio.git"
  AZURE_SUBSCRIPTION: "worldsys-complianceevolution(713d2774-b69b-4e66-b38e-2626b4b74b1d)"
  ARGOCD_SERVER: "argocd.worldsysweb.com"
