name: Post-Merge Actions

on:
  push:
    branches:
      - main
      - develop      

jobs:  
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{env.PROJECT_NAME}}
        path: ./path/to/publish  # Ruta donde se publica la aplicación

    - name: Set environment
      run: |    
        if [[ $GITHUB_REF == refs/heads/main ]]; then
            # Despliegue a entorno de producción
            echo "Deploying to production..."            
            env:
            ENVIRONMENT: "production"            
        elif [[ $GITHUB_REF == refs/heads/develop ]]; then            
            echo "Deploying to staging..."            
            env:
            ENVIRONMENT: "development"            
        else
            # Despliegue para otras ramas (feature, release, hotfix)
            echo "Skipping deployment for non-main/develop branches."
        fi

    - name: Login to Azure Container Registry
      run: |
        echo "Login to Azure Container Registry REGISTRY_URL:${{secrets.secrets.REGISTRY_URL}} REGISTRY_USERNAME:${{ secrets.REGISTRY_USERNAME }} REGISTRY_PASSWORD:${{ secrets.REGISTRY_PASSWORD }}"
          # uses: azure/docker-login@v1
          # with:
          #   login-server: ${{ secrets.REGISTRY_URL }}
          #   username: ${{ secrets.REGISTRY_USERNAME }}
          #   password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: |
        echo "docker build -t ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}""
        # run: docker build -t ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }} .

    - name: Push Docker image to registry
      run: |
        echo "docker push ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}"
        # run: docker push ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}

    - name: Deploy using ArgoCD
      run: |
        echo  "deploy ambiente $ENVIRONMENT argocd https://${env.ARGOCD_SERVER}/download/argocd-linux-amd64"
      # run: |
      #   curl -sSL -o argocd --insecure https://${env.ARGOCD_SERVER}/download/argocd-linux-amd64
      #             chmod +x argocd
      #             echo ./argocd app set "${{ parameters.environment }}-${{ parameters.project_name }}" --revision ${{ parameters.app_version }}
      #             ./argocd app set "${{ parameters.environment }}-${{ parameters.project_name }}" --revision ${{ parameters.app_version }}
