name: Post-Merge Actions

on:
  push:
    branches:
      - main
      - develop      
env:      
      PROJECT_NAME: 'dotnet-core-template'
      CSPROJ_PATH: './Worldsys.API/Worldsys.API.csproj'
      SLN_PATH: "./*.sln"
      REPOSITORY_URL: "https://github.com/tu-usuario/tu-repositorio.git"
      AZURE_SUBSCRIPTION: "worldsys-complianceevolution(713d2774-b69b-4e66-b38e-2626b4b74b1d)"
      ARGOCD_SERVER: "argocd.worldsysweb.com"
      APP_VERSION: ${{github.run_id}}
      DOCKER_FILE: "./Dockerfile"
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:  
  build:
    runs-on: ubuntu-latest
   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release -o build ${{ env.CSPROJ_PATH}}

    - name: Publish artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
          name: ${{ env.PROJECT_NAME }}-build
          path: ${{ github.workspace }}/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Verificar contenido del directorio de artefactos
      run: ls -R ${{ github.workspace }}/build-artifacts

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ github.workspace }}/build-artifacts/${{ env.PROJECT_NAME }}-build
        path: ${{ github.workspace }}/build-artifacts

    - name: Login to Azure Container Registry
      run: |
        echo "Login to Azure Container Registry REGISTRY_URL:${{secrets.REGISTRY_URL}} REGISTRY_USERNAME:${{ secrets.REGISTRY_USERNAME }} REGISTRY_PASSWORD:${{ secrets.REGISTRY_PASSWORD }}"
          # uses: azure/docker-login@v1
          # with:
          #   login-server: ${{ secrets.REGISTRY_URL }}
          #   username: ${{ secrets.REGISTRY_USERNAME }}
          #   password: ${{ secrets.REGISTRY_PASSWORD }}

    # - name: Build Docker image
    #   run:     
    #     docker build -t .
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.workspace }}/build-artifacts/${{ env.PROJECT_NAME }}-build
        file: ${{ env.DOCKER_FILE }}
        push: false
        tags: |
          ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ env.APP_VERSION }}
        build-args: |
          APP_VERSION=${{ env.APP_VERSION }}
          

    - name: Push Docker image to registry
      run: |
        echo "docker push ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}"
        # run: docker push ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}

    # - name: Ejecutar análisis de vulnerabilidades con Trivy
    #   uses: aquasecurity/trivy-action@v2
    #   with:
    #     image: ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ env.APP_VERSION }}

    - name: Set environment
      run: |    
        if [[ $GITHUB_REF == refs/heads/main ]]; then
            # Despliegue a entorno de producci�n
            echo "Deploying to production..."            
            echo "ENVIRONMENT=production" >> $GITHUB_ENV         
        elif [[ $GITHUB_REF == refs/heads/develop ]]; then            
            echo "Deploying to development..."                        
            echo "ENVIRONMENT=development" >> $GITHUB_ENV            
        else
            # Despliegue para otras ramas (feature, release, hotfix)
            echo "Skipping deployment for non-main/develop branches."
        fi

    - name: Deploy using ArgoCD
      run: |
        echo  "deploy ambiente ${{env.ENVIRONMENT}} argocd https://${env.ARGOCD_SERVER}/download/argocd-linux-amd64"
      # run: |
      #   curl -sSL -o argocd --insecure https://${env.ARGOCD_SERVER}/download/argocd-linux-amd64
      #             chmod +x argocd
      #             echo ./argocd app set "${{ parameters.environment }}-${{ parameters.project_name }}" --revision ${{ parameters.app_version }}
      #             ./argocd app set "${{ parameters.environment }}-${{ parameters.project_name }}" --revision ${{ parameters.app_version }}
