name: Build and Deploy

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened]
      # - 'develop'           
      # - 'hotfix/*'
      # - 'bugfix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha}}
      - name: Pull and checking out from git repository
        run: |
           echo "Pull and checking out from git repository finished Ok"
           
      - name: Validate branch name
        run: |
          PR_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          if [[ "$PR_BRANCH" != feature/* && "$PR_BRANCH" != hotfix/* && "$PR_BRANCH" != bugfix/* ]]; then
            echo "Pull requests are only allowed from branches with feature, hotfix, or bugfix names."
            exit 1
          fi

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release
        
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
            name: dotnet-core-template
            path: ./path/to/publish  # Ruta donde se publica la aplicación
