name: Build and Docker Build

on:
  repository_dispatch: 
    types: [build-pipeline-event]
env:          
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:  
  # build_project:
  #   runs-on: ubuntu-latest
   
  #   steps:
  #   - name: Control de variables.
  #     run: |
  #       echo imprimo variables DEPLOY_TO_DEV: ${{github.event.client_payload.DEPLOY_TO_DEV}}, DEPLOY_TO_QA: ${{github.event.client_payload.DEPLOY_TO_QA}}, DEPLOY_TO_UAT: ${{github.event.client_payload.DEPLOY_TO_UAT}}, DEPLOY_TO_PROD: ${{github.event.client_payload.DEPLOY_TO_PROD}}, REGISTRY_SERVER_NAME: ${{github.event.client_payload.REGISTRY_SERVER_NAME}}, base_ref: ${{github.event.client_payload.base_ref}}

  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #     with:
  #       ref: ${{ github.event.client_payload.base_branch }}
      
  #   - name: Setup .NET Core SDK
  #     uses: actions/setup-dotnet@v1.5.0
  #     with:
  #       dotnet-version: '8.0.x'
        
  #   - name: Restore dependencies
  #     run: dotnet restore

  #   - name: Build
  #     run: dotnet build -c Release -o build ${{ github.event.client_payload.CSPROJ_PATH }}

  build_img_docker:
    runs-on: ubuntu-latest
    # needs: build_project

    steps:

    - name: Find Dockerfile
      run: |
        find $GITHUB_WORKSPACE -name Dockerfile

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.base_branch }}        

    # - name: Login to Azure Container Registry
    #   uses: azure/docker-login@v1
    #   with:
    #     login-server: ${{ secrets.REGISTRY_URL }}        
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}    
    #     # run: |
    #     #   docker build . -t ${{ github.event.client_payload.REGISTRY_SERVER_NAME }}/${{ github.event.client_payload.PROJECT_NAME }}:${{ github.event.client_payload.APP_VERSION }}
    #     #   docker push ${{ github.event.client_payload.REGISTRY_SERVER_NAME }}/${{ github.event.client_payload.PROJECT_NAME }}:${{ github.event.client_payload.APP_VERSION }}

    # OPCION 1
    # - uses: mr-smithers-excellent/docker-build-push@v6
    #   name: Build & push Docker image
    #   with:
    #     image: ${{ github.event.client_payload.REGISTRY_SERVER_NAME }}/${{ github.event.client_payload.PROJECT_NAME }}:${{ github.event.client_payload.APP_VERSION }}
    #     tags: v1, latest
    #     registry: ${{ github.event.client_payload.REGISTRY_SERVER_NAME }}
    #     dockerfile: ${{ github.event.client_payload.DOCKER_FILE }}
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}

    # OPCION 2
    # - name: Build Docker image
    #   uses: docker/build-push-action@v2
    #   with:        
    #     context: .
    #     file: ${{ github.event.client_payload.DOCKER_FILE }}
    #     push: true
    #     tags: |
    #       ${{ github.event.client_payload.REGISTRY_SERVER_NAME }}/${{ github.event.client_payload.PROJECT_NAME }}:${{ github.event.client_payload.APP_VERSION }}


    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
          charts_dir: "./helpm"
          config: "/helm/Chart.yaml"
      env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
    - name: Ejecutar análisis de vulnerabilidades con Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ github.event.client_payload.REGISTRY_SERVER_NAME }}/${{ github.event.client_payload.PROJECT_NAME }}:${{ github.event.client_payload.APP_VERSION }}
