name: Initial Pipeline

on:
  push:
    branches:
      - release/*
      - develop
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - release/*
      - hotfix/*
    
env:          
    DEPLOY_TO_DEV: ${{ contains(github.ref, 'develop') || contains(github.ref, 'feature') }}
    DEPLOY_TO_QA: ${{ contains(github.ref, 'release') || contains(github.ref, 'bugfix') }}
    DEPLOY_TO_UAT: ${{ contains(github.ref, 'release') || contains(github.ref, 'hotfix') }}
    DEPLOY_TO_PROD: ${{ contains(github.ref, 'release') || contains(github.ref, 'hotfix') }}
    REGISTRY_SERVER_NAME: ${{ (github.event_name == 'pull_request' || contains(github.ref, 'develop') || contains(github.ref, 'feature')) && 'crwsnonprodeastus001.azurecr.io' || (contains(github.ref, 'release') || contains(github.ref, 'bugfix') || contains(github.ref, 'hotfix')) && 'crwsprodbrazilsouth001.azurecr.io' }}

    PROJECT_NAME: 'dotnet-core-template'
    CSPROJ_PATH: './Worldsys.API/Worldsys.API.csproj'
    SLN_PATH: "./*.sln"      
    ARGOCD_SERVER: "argocd.worldsysweb.com"
    APP_VERSION: ${{github.run_id}}
    DOCKER_FILE: "./Worldsys.API/Dockerfile"    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:  
        
      - name: Control de variables.
        run: |
          echo imprimo variables repository: ${{ github.repository }} token: ${{ secrets.GITHUB_TOKEN }} githubhead_ref: ${{github.head_ref}}  githubref: ${{ github.ref }} githubbase_ref: ${{ github.base_ref}} BRANCH_NAME: ${{github.ref_name}} REGISTRY_SERVER_NAME: ${{env.REGISTRY_SERVER_NAME}} EVENT_NAME: ${{github.event_name}} DEPLOY_TO_DEV: ${{env.DEPLOY_TO_DEV}}, DEPLOY_TO_QA: ${{env.DEPLOY_TO_QA}}, DEPLOY_TO_UAT: ${{env.DEPLOY_TO_UAT}}, DEPLOY_TO_PROD: ${{env.DEPLOY_TO_PROD}}, REGISTRY_SERVER_NAME: ${{env.REGISTRY_SERVER_NAME}}          

      - name: Build and Docker Build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: build-pipeline-event
          client-payload: '{"ref": "${{ github.ref }}", "base_branch": "${{ github.base_ref}}" , "REGISTRY_SERVER_NAME": "${{env.REGISTRY_SERVER_NAME}}", "PROJECT_NAME": "${{env.PROJECT_NAME}}", "CSPROJ_PATH": "${{env.CSPROJ_PATH}}", "APP_VERSION": "${{env.APP_VERSION}}", "DOCKER_FILE": "${{env.DOCKER_FILE}}" }'

  
  # deploy_to_dev:
  #     runs-on: ubuntu-latest
  #     needs: build
  #     if: ${{ env.DEPLOY_TO_DEV == 'true'}}
  #     steps:
  #       - name: Deploy to Dev - Helm build and Deploy process
  #         uses: peter-evans/repository-dispatch@v3
  #         with:
  #           # token: ${{ secrets.PAT }}
  #           repository: $ {{ github.repository }}
  #           event-type: deploy-pipeline-event
  #           client-payload: '{ environment: "dev", PROJECT_NAME: ${{env.PROJECT_NAME}}, APP_VERSION: ${{env.APP_VERSION}}}'
  # deploy_to_qa:
  #     runs-on: ubuntu-latest
  #     needs: build
  #     if: ${{ env.DEPLOY_TO_QA == 'true'}}
  #     steps:
  #       - name: Deploy to Qa - Helm build and Deploy process
  #         uses: peter-evans/repository-dispatch@v3
  #         with:
  #           # token: ${{ secrets.PAT }}
  #           repository: $ {{ github.repository }}
  #           event-type: deploy-pipeline-event
  #           client-payload: '{ environment: "qa", PROJECT_NAME: ${{env.PROJECT_NAME}}, APP_VERSION: ${{env.APP_VERSION}}}'  
  # deploy_to_prod:
  #     runs-on: ubuntu-latest
  #     needs: build
  #     if: ${{ env.DEPLOY_TO_PROD == 'true'}}
  #     steps:
  #       - name: Deploy to Prod - Helm build and Deploy process
  #         uses: peter-evans/repository-dispatch@v3
  #         with:
  #           # token: ${{ secrets.PAT }}
  #           repository: $ {{ github.repository }}
  #           event-type: deploy-pipeline-event
  #           client-payload: '{ environment: "prod", PROJECT_NAME: ${{env.PROJECT_NAME}}, APP_VERSION: ${{env.APP_VERSION}}}'

  