name: Initial Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - release/*
      - develop
      - 'hotfix/*'
  # pull_request:
  #   branches:
  #     - develop
  #     - release/*
  #     - hotfix/*
   
env:   
    IS_DEPLOY: ${{ github.event_name != 'pull_request' }}
    DEPLOY_TO_DEV:  ${{ github.event_name != 'pull_request' && contains(github.ref, 'develop') || contains(github.ref, 'feature') }}
    DEPLOY_TO_QA: ${{github.event_name != 'pull_request' && contains(github.ref, 'release') || contains(github.ref, 'bugfix') }}
    DEPLOY_TO_UAT: ${{github.event_name != 'pull_request' && contains(github.ref, 'release') || contains(github.ref, 'hotfix') }}
    DEPLOY_TO_PROD: ${{github.event_name != 'pull_request' && contains(github.ref, 'release') || contains(github.ref, 'hotfix') }}
    REGISTRY_SERVER_NAME: ${{ (github.event_name == 'pull_request' || contains(github.ref, 'develop') || contains(github.ref, 'feature')) && 'crwsnonprodeastus001.azurecr.io' || (contains(github.ref, 'release') || contains(github.ref, 'bugfix') || contains(github.ref, 'hotfix')) && 'crwsprodbrazilsouth001.azurecr.io' }}
    PROJECT_NAME: 'dotnet-core-template'
    CSPROJ_PATH: './Worldsys.API/Worldsys.API.csproj'
    SLN_PATH: "./*.sln"      
    ARGOCD_SERVER: "argocd.worldsysweb.com"
    APP_VERSION: ${{ github.run_id }}
    DOCKER_FILE: "./Worldsys.API/Dockerfile"    
    CHART_PATH: "./Worldsys.API/helm/"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:  
        
      - name: Control de variables.
        run: |
          echo imprimo variables EVENTO: ${{ github.event_name }}  IS_DEPLOY: ${{env.IS_DEPLOY}} repository: ${{ github.repository }} token: ${{ secrets.GITHUB_TOKEN }} githubhead_ref: ${{github.head_ref}}  githubref: ${{ github.ref }} githubbase_ref: ${{ github.base_ref}} BRANCH_NAME: ${{github.ref_name}} REGISTRY_SERVER_NAME: ${{env.REGISTRY_SERVER_NAME}} EVENT_NAME: ${{github.event_name}} DEPLOY_TO_DEV: ${{env.DEPLOY_TO_DEV}}, DEPLOY_TO_QA: ${{env.DEPLOY_TO_QA}}, DEPLOY_TO_UAT: ${{env.DEPLOY_TO_UAT}}, DEPLOY_TO_PROD: ${{env.DEPLOY_TO_PROD}}, REGISTRY_SERVER_NAME: ${{env.REGISTRY_SERVER_NAME}}          

      - name: Checkout repository
        if: success()
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}        

      - uses: mr-smithers-excellent/docker-build-push@v6
        if: success()
        name: build & push docker image
        with:
          image: ${{ env.PROJECT_NAME }}
          tags: ${{ env.APP_VERSION }}
          registry: ${{ env.REGISTRY_SERVER_NAME }}
          dockerfile: ${{ env.DOCKER_FILE }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Ejecutar análisis de vulnerabilidades con Trivy
        if: success()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY_SERVER_NAME }}/${{ env.PROJECT_NAME }}:${{ env.APP_VERSION }}          
        
      - name: Replace Values in Chart
        if: success()
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "#{"
          tokenSuffix: "}#"
          files: '["**/helm/*.yaml"]'
        env:
          registry_server_name: ${{ env.REGISTRY_SERVER_NAME }}
          project_name: ${{ env.PROJECT_NAME }}
          app_version: ${{ env.APP_VERSION }}

          
      - name: Install Helm
        if: success()
        uses: azure/setup-helm@v3

      
      - name: Log in to Azure Container Registry
        if: success()
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_SERVER_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Package Chart
        if: success()
        run: |
          helm package ${{ env.CHART_PATH }} --version ${{ env.APP_VERSION }}
          chart_file=$(find . -type f -name "*.tgz")          
          echo "::set-output name=chartFile::$chart_file"
        id: packageChart           
        

      - name: Push Chart to ${{ env.REGISTRY_SERVER_NAME }}/helmcharts
        if: success()
        run: |
          helm push  ${{ steps.packageChart.outputs.chartFile }}  oci://${{ env.REGISTRY_SERVER_NAME }}/helmcharts        

            
  deploy_to_dev:    
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [build]
    if: ((github.event_name != 'pull_request' && contains(github.ref, 'develop') || contains(github.ref, 'feature'))  && success())
    steps:
      - name: Deploy to Dev - Helm build and Deploy process
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          repository: $ {{ github.repository }}
          event-type: deploy-pipeline-event
          client-payload: '{ "environment": "dev", "PROJECT_NAME": "${{ env.PROJECT_NAME }}", "APP_VERSION": "${{ env.APP_VERSION }}" }'
  deploy_to_qa:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [build]
    if: ((github.event_name != 'pull_request' && contains(github.ref, 'release') || contains(github.ref, 'bugfix')) && success())
    steps:
      - name: Deploy to Qa - Helm build and Deploy process
        uses: peter-evans/repository-dispatch@v3
        with:
          # token: ${{ secrets.PAT }}
          repository: $ {{ github.repository }}
          event-type: deploy-pipeline-event
          client-payload: '{ environment: "qa", PROJECT_NAME: ${{env.PROJECT_NAME}}, APP_VERSION: ${{env.APP_VERSION}}}'  
  deploy_to_prod:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [build]
    if: ((github.event_name != 'pull_request' && contains(github.ref, 'release') || contains(github.ref, 'hotfix')) && success())
    steps:
      - name: Deploy to Prod - Helm build and Deploy process
        uses: peter-evans/repository-dispatch@v3
        with:
          # token: ${{ secrets.PAT }}
          repository: $ {{ github.repository }}
          event-type: deploy-pipeline-event
          client-payload: '{ environment: "prod", PROJECT_NAME: ${{env.PROJECT_NAME}}, APP_VERSION: ${{env.APP_VERSION}}}'

  